name: Build test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - '19*'
  push:
    branches:
      - '19*'

jobs:
  run-tests:
    uses: tawasta/github-workflows/.github/workflows/odoo-19-build-test.yml@main
    secrets: inherit